### ISSUE TITLE
Beacon IOError

### ISSUE THREAD

**Issue by daniwhite** [daniwhite/BikeIoT#3]
After about a minute, beacon crashes with this error:

```
Traceback (most recent call last):
  File "Beacon.py", line 136, in <module>
    loudness = grovepi.analogRead(LOUDNESS_SENSOR)
  File "/home/pi/Desktop/GrovePi/Software/Python/grovepi.py", line 221, in analogRead
    number = bus.read_i2c_block_data(address, 1)
IOError: [Errno 5] Input/output error
```

**Comment by daniwhite** [comment]
See this forum post: http://www.dexterindustries.com/topic/ioerror-and-installation-issues/

**Comment by daniwhite** [comment]
Thought that fixing #1 and #4 would fix this, but it didn't. So the temp fix is probably fine.
